# Generated by Django 5.2.5 on 2025-12-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_service_description_en_service_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
