# Generated by Django 5.2.5 on 2026-06-02 05:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_refactor_staff_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staff',
            new_name='app_staff_is_acti_382f90_idx',
            old_name='app_staff_is_acti_idx',
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='F.I.O'),
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='F.I.O'),
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='F.I.O'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Lavozim'),
        ),
        migrations.AddField(
            model_name='staff',
            name='practice_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Amaliyot'),
        ),
        migrations.AddField(
            model_name='staff',
            name='practice_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Amaliyot'),
        ),
        migrations.AddField(
            model_name='staff',
            name='practice_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Amaliyot'),
        ),
        migrations.AddField(
            model_name='staff',
            name='short_description_en',
            field=models.CharField(blank=True, help_text="Card ostida ko'rinadigan 1-2 qatorlik qisqa matn.", max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='staff',
            name='short_description_ru',
            field=models.CharField(blank=True, help_text="Card ostida ko'rinadigan 1-2 qatorlik qisqa matn.", max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='staff',
            name='short_description_uz',
            field=models.CharField(blank=True, help_text="Card ostida ko'rinadigan 1-2 qatorlik qisqa matn.", max_length=300, null=True, verbose_name='Qisqa tavsif'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Mutaxassislik'),
        ),
    ]
