# Generated by Django 5.2.5 on 2026-06-02 06:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_refactor_staff_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staff',
            new_name='app_staff_is_acti_382f90_idx',
            old_name='app_staff_is_acti_idx',
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='F.I.O (EN)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='F.I.O (RU)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozim (EN)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lavozim (RU)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='practice_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Amaliyot (EN)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='practice_ru',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Amaliyot (RU)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Mutaxassislik (EN)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='specialization_ru',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Mutaxassislik (RU)'),
        ),
    ]
