# Generated by Django 5.2.17 on 2026-09-18 05:07

import app.models
import app.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


from django.utils.text import slugify


def fill_slugs(apps, schema_editor):
    """Mavjud yo'nalish va xizmatlarga nomidan takrorlanmas slug beradi."""
    for model_name, source, fallback in (("ServiceCategory", "name", "xizmat"), ("Service", "title", "xizmat")):
        model = apps.get_model("app", model_name)
        used = set()
        for obj in model.objects.order_by("id"):
            base = slugify(getattr(obj, source)) or fallback
            slug, i = base, 2
            while slug in used:
                slug = f"{base}-{i}"
                i += 1
            used.add(slug)
            obj.slug = slug
            obj.save(update_fields=["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_app_staff_is_acti_idx_app_staff_is_acti_382f90_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Masalan: 1200+ yoki 15', max_length=20, verbose_name='Qiymat')),
                ('label', models.CharField(help_text='Masalan: yutilgan ish', max_length=100, verbose_name='Izoh')),
                ('label_ru', models.CharField(blank=True, max_length=100, verbose_name='Izoh (RU)')),
                ('label_en', models.CharField(blank=True, max_length=100, verbose_name='Izoh (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Ko'rsatkich",
                'verbose_name_plural': "Ko'rsatkichlar (raqamlar)",
                'ordering': ('order', 'id'),
            },
            bases=(app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('privacy', 'Maxfiylik siyosati'), ('terms', 'Foydalanish shartlari')], max_length=20, unique=True, verbose_name='Sahifa')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Sarlavha (EN)')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn')),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Matn (RU)')),
                ('body_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Matn (EN)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Huquqiy sahifa',
                'verbose_name_plural': 'Huquqiy sahifalar',
            },
            bases=(app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', models.CharField(default='+998555122992', max_length=32, verbose_name='Asosiy telefon')),
                ('phone_secondary', models.CharField(blank=True, default='+998998088889', max_length=32, verbose_name="Qo'shimcha telefon")),
                ('email', models.EmailField(default='Liberator.inbox@gmail.com', max_length=254, verbose_name='Email')),
                ('address', models.CharField(default='Toshkent shahri, Yashnobod tumani, Sodiq Azimov ko‘chasi 68-uy', max_length=255, verbose_name='Manzil')),
                ('address_ru', models.CharField(blank=True, default='г. Ташкент, Яшнабадский район, ул. Садыка Азимова, 68', max_length=255, verbose_name='Manzil (RU)')),
                ('address_en', models.CharField(blank=True, default='68 Sodiq Azimov Street, Yashnobod District, Tashkent', max_length=255, verbose_name='Manzil (EN)')),
                ('working_hours', models.CharField(default='Dushanba–Shanba: 09:00 – 18:00', max_length=120, verbose_name='Ish vaqti')),
                ('working_hours_ru', models.CharField(blank=True, default='Понедельник–Суббота: 09:00 – 18:00', max_length=120, verbose_name='Ish vaqti (RU)')),
                ('working_hours_en', models.CharField(blank=True, default='Mon–Sat: 09:00 – 18:00', max_length=120, verbose_name='Ish vaqti (EN)')),
                ('latitude', models.DecimalField(decimal_places=6, default=41.303795, max_digits=9, verbose_name='Kenglik')),
                ('longitude', models.DecimalField(decimal_places=6, default=69.288944, max_digits=9, verbose_name='Uzunlik')),
                ('telegram_url', models.URLField(blank=True, help_text='Masalan: https://t.me/liberator_uz', verbose_name='Telegram')),
                ('whatsapp_phone', models.CharField(blank=True, help_text='Faqat raqamlar, masalan: 998998088889', max_length=32, verbose_name='WhatsApp raqami')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('founded_year', models.PositiveIntegerField(default=2010, verbose_name='Asos solingan yil')),
                ('meta_description', models.CharField(blank=True, default='Liberator advokatlik firmasi — korporativ, fuqarolik, iqtisodiy va jinoyat ishlari bo‘yicha malakali yuridik yordam. Bepul konsultatsiya.', help_text="Google natijalarida ko'rinadigan 150–160 belgilik tavsif.", max_length=160, verbose_name='SEO tavsif')),
                ('meta_description_ru', models.CharField(blank=True, default='Адвокатская фирма Liberator — корпоративное, гражданское, экономическое и уголовное право в Ташкенте. Бесплатная консультация.', max_length=160, verbose_name='SEO tavsif (RU)')),
                ('meta_description_en', models.CharField(blank=True, default='Liberator law firm in Tashkent — corporate, civil, commercial and criminal law. Free initial consultation.', max_length=160, verbose_name='SEO tavsif (EN)')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
            bases=(app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150, verbose_name='Mijoz ismi')),
                ('author_position', models.CharField(blank=True, max_length=150, verbose_name='Lavozimi / kompaniya')),
                ('author_position_ru', models.CharField(blank=True, max_length=150, verbose_name='Lavozimi (RU)')),
                ('author_position_en', models.CharField(blank=True, max_length=150, verbose_name='Lavozimi (EN)')),
                ('text', models.TextField(verbose_name='Sharh')),
                ('text_ru', models.TextField(blank=True, verbose_name='Sharh (RU)')),
                ('text_en', models.TextField(blank=True, verbose_name='Sharh (EN)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[app.utils.validate_image_size], verbose_name='Rasm')),
                ('consent_received', models.BooleanField(default=False, help_text="Sharh faqat mijozning yozma roziligi bilan e'lon qilinadi.", verbose_name='Mijoz roziligi olingan')),
                ('is_published', models.BooleanField(default=False, verbose_name="E'lon qilingan")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Mijoz sharhi',
                'verbose_name_plural': 'Mijozlar sharhlari',
                'ordering': ('order', '-id'),
            },
            bases=(app.utils.OptimizedImagesMixin, app.models.LocalizedMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='casestatistic',
            options={'verbose_name': 'Ish (ichki hisob)', 'verbose_name_plural': 'Ishlar (ichki hisob)'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Hamkor', 'verbose_name_plural': 'Hamkorlar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ('order', 'id'), 'verbose_name': "Xizmat yo'nalishi", 'verbose_name_plural': "Xizmat yo'nalishlari"},
        ),
        migrations.AddField(
            model_name='partner',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, default='', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Tartib'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL uchun: /uz/xizmatlar/<slug>/. Bo'sh qoldirilsa nomdan yasaladi.", max_length=120, default='', verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='staff',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif (EN)'),
        ),
        migrations.AddField(
            model_name='staff',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Qisqa tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='case_type',
            field=models.CharField(choices=[('criminal', 'Jinoyat ishi'), ('civil', 'Fuqarolik ishi'), ('administrative', "Ma'muriy ish"), ('economic', 'Iqtisodiy ish')], max_length=20, verbose_name='Ish turi'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='client_name',
            field=models.CharField(max_length=200, verbose_name='Mijoz'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='closed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Yopilgan'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='opened_at',
            field=models.DateField(auto_now_add=True, verbose_name='Ochilgan'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='app.service', verbose_name='Xizmat'),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul"),
        ),
        migrations.AlterField(
            model_name='casestatistic',
            name='status',
            field=models.CharField(default='open', max_length=50, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='icon',
            field=models.ImageField(blank=True, help_text='Hamkor logotipi (faqat ularning roziligi bilan).', null=True, upload_to='partners/icons/', validators=[app.utils.validate_image_size], verbose_name='Logotip'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('lawyer', 'Advokat'), ('company', 'Kompaniya'), ('organization', 'Tashkilot'), ('other', 'Boshqa')], default='other', max_length=50, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Veb-sayt'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='app.servicecategory', verbose_name="Yo'nalish"),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (EN)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_categories/%Y/%m/%d', validators=[app.utils.validate_image_size], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomi (EN)'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nomi (RU)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, help_text='Tavsiya: 600x700px. Yuklangan rasm avtomatik siqiladi (WebP).', null=True, upload_to='staff/%Y/%m/', validators=[app.utils.validate_image_size], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='practice',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Amaliyot'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='practice_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Amaliyot (EN)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='practice_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Amaliyot (RU)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Mutaxassislik'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Mutaxassislik (EN)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='specialization_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Mutaxassislik (RU)'),
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consultation', 'Konsultatsiya'), ('callback', "Qayta qo'ng'iroq")], default='consultation', max_length=20, verbose_name='Turi')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ism')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Telefon raqamini to'g'ri kiriting, masalan: +998 90 123 45 67", regex='^\\+?[\\d\\s\\-()]{9,20}$')], verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('source_page', models.CharField(blank=True, max_length=255, verbose_name='Qaysi sahifadan')),
                ('language', models.CharField(blank=True, max_length=5, verbose_name='Til')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('in_progress', 'Jarayonda'), ('closed', 'Yopildi'), ('spam', 'Spam')], db_index=True, default='new', max_length=20, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yuborilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app.servicecategory', verbose_name="Yo'nalish")),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='app.staff', verbose_name='Advokat')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Savol')),
                ('question_ru', models.CharField(blank=True, max_length=255, verbose_name='Savol (RU)')),
                ('question_en', models.CharField(blank=True, max_length=255, verbose_name='Savol (EN)')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('answer_ru', models.TextField(blank=True, verbose_name='Javob (RU)')),
                ('answer_en', models.TextField(blank=True, verbose_name='Javob (EN)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('category', models.ForeignKey(blank=True, help_text="Bo'sh bo'lsa — umumiy savol (aloqa sahifasida chiqadi).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faqs', to='app.servicecategory', verbose_name="Yo'nalish")),
            ],
            options={
                'verbose_name': 'Savol-javob',
                'verbose_name_plural': "Ko'p beriladigan savollar",
                'ordering': ('order', 'id'),
            },
            bases=(app.models.LocalizedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(blank=True, max_length=220, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=220, verbose_name='Sarlavha (EN)')),
                ('summary', models.CharField(blank=True, help_text="Ro'yxatda va Google'da ko'rinadi (150–160 belgi ideal).", max_length=300, verbose_name='Qisqa mazmun')),
                ('summary_ru', models.CharField(blank=True, max_length=300, verbose_name='Qisqa mazmun (RU)')),
                ('summary_en', models.CharField(blank=True, max_length=300, verbose_name='Qisqa mazmun (EN)')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Matn')),
                ('body_ru', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Matn (RU)')),
                ('body_en', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Matn (EN)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', validators=[app.utils.validate_image_size], verbose_name='Rasm')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name="E'lon qilingan")),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name="E'lon qilingan sana")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='app.staff', verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Yangiliklar va maqolalar',
                'ordering': ('-published_at',),
            },
            bases=(app.utils.OptimizedImagesMixin, app.models.LocalizedMixin, models.Model),
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL uchun: /uz/xizmatlar/<slug>/. Bo'sh qoldirilsa nomdan yasaladi.", max_length=120, unique=True, verbose_name='Slug'),
        ),
    ]
