# Generated by Django 5.2.17 on 2026-09-18 07:36

from django.db import migrations, models



def fill_translated_slugs(apps, schema_editor):
    """Mavjud yozuvlarga ruscha va inglizcha nomidan slug yasaydi."""
    from django.utils.text import slugify

    from app.utils import transliterate

    for model_name, source in (("ServiceCategory", "name"), ("Service", "title"), ("News", "title")):
        model = apps.get_model("app", model_name)
        for lang in ("ru", "en"):
            used = set(model.objects.exclude(**{f"slug_{lang}": None}).values_list(f"slug_{lang}", flat=True))
            for obj in model.objects.filter(**{f"slug_{lang}": None}).order_by("id"):
                value = getattr(obj, f"{source}_{lang}")
                if not value:
                    continue
                base = slugify(transliterate(value)) or obj.slug
                slug, i = base, 2
                while slug in used:
                    slug = f"{base}-{i}"
                    i += 1
                used.add(slug)
                setattr(obj, f"slug_{lang}", slug)
                obj.save(update_fields=[f"slug_{lang}"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_seed_site_settings_and_legal_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=240, null=True, unique=True, verbose_name='Slug (EN)'),
        ),
        migrations.AddField(
            model_name='news',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=240, null=True, unique=True, verbose_name='Slug (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='Slug (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_ru',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True, verbose_name='Slug (RU)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug_en',
            field=models.SlugField(blank=True, help_text="Bo'sh qoldirilsa inglizcha nomdan yasaladi.", max_length=120, null=True, unique=True, verbose_name='Slug (EN)'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='slug_ru',
            field=models.SlugField(blank=True, help_text="Bo'sh qoldirilsa ruscha nomdan yasaladi.", max_length=120, null=True, unique=True, verbose_name='Slug (RU)'),
        ),
        migrations.RunPython(fill_translated_slugs, migrations.RunPython.noop),
    ]
